name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-musl
          override: true

      - name: Install cross-compile tools
        run: sudo apt-get install -y gcc-aarch64-linux-gnu musl-tools

      - name: Build aarch64
        run: |
          cargo build --release --target aarch64-unknown-linux-musl
          mkdir -p docs/binaries
          cp target/aarch64-unknown-linux-musl/release/gitgrade docs/binaries/gitgrade-aarch64

      - name: Build x86_64
        run: |
          rustup target add x86_64-unknown-linux-musl
          cargo build --release --target x86_64-unknown-linux-musl
          cp target/x86_64-unknown-linux-musl/release/gitgrade docs/binaries/gitgrade-x86_64

      - name: Commit binaries
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add docs/binaries/
          git diff --staged --quiet || git commit -m "add compiled binaries"
          git push
